name: Terraform validate
description: Perform terraform checks

inputs:
  terraform-version:
    description: 'Terraform version to use'
    required: false
    type: string
    default: 'latest'
  terraform-docs-version:
    description: 'Terraform-docs version to use'
    required: false
    type: string
    default: 'latest'
  tflint-version:
    description: 'TFLint version to use'
    required: false
    type: string
    default: 'latest'
  trivy-version:
    description: 'Trivy version to use'
    required: false
    type: string
    default: 'latest'
  checkov-version:
    description: 'Checkov version to use'
    required: false
    type: string
    default: 'latest'

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: 3

    - name: Setup go
      uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
      with:
        go-version: 'stable'
        cache: false # not applicable since we don't use module dependencies `go.mod`

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
      with:
        terraform_version: ${{ inputs.terraform-version }}

    - name: Setup Trivy
      uses: aquasecurity/setup-trivy@e6c2c5e321ed9123bda567646e2f96565e34abe1 # v0.2.4
      with:
        version: ${{ inputs.trivy-version }}

    - name: Install Checkov
      shell: bash
      run: |
        echo "Install Checkov"
        package_spec="checkov"
        [ "${{ inputs.checkov-version }}" != "latest" ] && package_spec+="==${{ inputs.checkov-version }}"
        pip install \
          -q \
          "$package_spec"

    - name: Install Go tools
      shell: bash
      run: |
        declare -A go_tools=(
          ["tflint"]="github.com/terraform-linters/tflint@${{ inputs.tflint-version }}"
          ["terraform-docs"]="github.com/terraform-docs/terraform-docs@${{ inputs.terraform-docs-version }}"
        )

        for t in "${!go_tools[@]}"; do
          echo "Install $t"
          go install "${go_tools[$t]}"
          echo
        done
