---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/terraform/deps/*"
      - "/comment-pr"
      - "/dispatcher"
      - "/pre-commit"
      - "/update-check"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "aquasecurity/setup-trivy" # temporary ignore
