name: Code Sanity Checks
description: |
  Run file formatting and structure checks via pre-commit hooks.
  These hooks have no standalone CLI equivalent so pre-commit is used selectively.

  This action is intentionally separate so it can be dropped or replaced independently.
  Maybe running these locally is enough

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    type: string
    default: '3.x'
  pre-commit-version:
    description: 'Pre-commit version to use'
    required: false
    type: string
    default: 'latest'

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: ${{ inputs.python-version }}

    - name: Code Sanity Checks
      shell: bash
      run: |
        echo "Install pre-commit"
        package_spec="pre-commit"

        version="${{ inputs.pre-commit-version || 'latest' }}"
        [ "$version" != "latest" ] && package_spec+="==$version"

        pip install -q "$package_spec"

        hooks=(
          check-added-large-files
          check-case-conflict
          check-json
          check-merge-conflict
          check-symlinks
          check-yaml
          end-of-file-fixer
          pretty-format-json
          trailing-whitespace
          check-shebang-scripts-are-executable
        )

        # Loop through and run each hook against all files
        for hook in "${hooks[@]}"; do
          echo "Running hook: $hook"
          if ! pre-commit run "$hook" --config .pre-commit-config.yaml --all-files; then
            echo "❌ Hook $hook failed! Displaying modified file changes below:"
            git diff
            exit 1
          fi
        done
