name: code-static-checks

on:
  push:
    branches:
      - main
      - EEF-35
  pull_request:
    branches:
      - main
      - EEF-35

permissions:
  contents: none
  id-token: none
  packages: none

jobs:
  terraform-checks:
    permissions:
      contents: read
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Run terraform checks
        uses: alphagov/gds-tech-and-security-github-actions/terraform-checks@9880d8986f60a509d41ca606a9d2af12cc33b643 # EEF-35
        with:
          checkov-version: 'latest'
          terraform-version: 'latest'
          working-directory: 'terraform'
          modules-directory: 'terraform/modules'
          tflint-config: '.tflint.hcl'
          terraform-docs-config: '.terraform-docs.yml'

  code-quality-security-analysis:
    permissions:
      contents: read
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Run code lint checks
        uses: alphagov/gds-tech-and-security-github-actions/code-quality-security-analysis@9880d8986f60a509d41ca606a9d2af12cc33b643 # EEF-35

  code-sanity-checks:
    permissions:
      contents: read
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Run code format checks
        uses: alphagov/gds-tech-and-security-github-actions/code-sanity-checks@9880d8986f60a509d41ca606a9d2af12cc33b643 # EEF-35
        with:
          pre-commit-version: 'latest'
