name: 'Dependency review'

on:
  pull_request:
    branches:
      - "main"

# NOTE: This declaration defaults all GH other permissions to none.
# - Create subsequent permissions scoped to job only after confirming with a techlead
# - Declaration here follows the policy defined in ADR-EA007
permissions:
  contents: none # Set so other permissions take the value 'none' by default
  id-token: none # Prevent OIDC token generation (‘none’ is the default)
  packages: none # Prevent package access (‘none’ is the default)

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: 'Dependency Review'
        uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v5.0.0
        with:
          fail-on-severity: moderate
          license-check: false
